@extends('v2.layout.layout')

@section('content')
    <main class="whitepaper-page">
        <section class="whitepaper-hero">
            <div class="container">
                <h1>{{ __('Disclaimer') }}</h1>
                <p>
                    {{ __('Important information about using :app, including platform availability, simulated game content, digital assets, third-party services and user responsibility.', ['app' => config('app.name')]) }}
                </p>
            </div>
        </section>

        <section class="whitepaper-body">
            <div class="container whitepaper-layout">
                <aside class="whitepaper-nav" aria-label="{{ __('Disclaimer contents') }}">
                    <strong>{{ __('Contents') }}</strong>
                    <a href="#overview" class="active">{{ __('Overview') }}</a>
                    <a href="#information">{{ __('Information Only') }}</a>
                    <a href="#gameplay">{{ __('Gameplay And Simulation') }}</a>
                    <a href="#assets">{{ __('Digital Assets') }}</a>
                    <a href="#availability">{{ __('Availability') }}</a>
                    <a href="#third-parties">{{ __('Third Parties') }}</a>
                    <a href="#liability">{{ __('Liability') }}</a>
                    <a href="#responsibility">{{ __('User Responsibility') }}</a>
                    <a href="#changes">{{ __('Changes') }}</a>
                </aside>

                <article class="whitepaper-content">
                    <section id="overview">
                        <h2>{{ __('General Disclaimer') }}</h2>
                        <p>
                            {{ __('This Disclaimer applies to the public website, platform features, marketplace pages, football management tools, token-related information and any other content made available through :app. By accessing or using the platform, you acknowledge that you have read and understood this Disclaimer.', ['app' => config('app.name')]) }}
                        </p>
                    </section>

                    <section id="information">
                        <h2>{{ __('1. Information Only') }}</h2>
                        <p>
                            {{ __('The information on this website is provided for general informational purposes only. While we aim to keep information accurate and up to date, we do not guarantee that all content is complete, current, error-free or suitable for every user or situation.') }}
                        </p>
                        <p>
                            {{ __('Nothing on this website should be interpreted as legal, financial, investment, tax or other professional advice. Users should obtain independent professional advice before making decisions that may have legal, financial or regulatory consequences.') }}
                        </p>
                    </section>

                    <section id="gameplay">
                        <h2>{{ __('2. Gameplay And Simulation') }}</h2>
                        <p>
                            {{ __('Match results, player ratings, club performance, marketplace values, tournament outcomes and other football-related content may be generated by game systems, simulations, algorithms or platform rules. These outputs are part of the entertainment and gameplay experience.') }}
                        </p>
                        <p>
                            {{ __('Simulated outcomes are not guarantees of future performance, asset value, user rewards or any real-world result. Platform mechanics may change as the game evolves.') }}
                        </p>
                    </section>

                    <section id="assets">
                        <h2>{{ __('3. Digital Assets And Token Information') }}</h2>
                        <p>
                            {{ __('Any information about tokens, digital assets, marketplace listings or platform economy features is provided for platform use and informational purposes. Digital assets may be volatile, may lose value and may be subject to technical, regulatory, liquidity and market risks.') }}
                        </p>
                        <p>
                            {{ __(':app does not guarantee the value, liquidity, availability or future utility of any digital asset. Users are responsible for understanding the risks before interacting with tokens, wallets, smart contracts or marketplace features.', ['app' => config('app.name')]) }}
                        </p>
                    </section>

                    <section id="availability">
                        <h2>{{ __('4. Platform Availability') }}</h2>
                        <p>
                            {{ __('We aim to provide a reliable service, but we do not guarantee uninterrupted access. The platform may be unavailable, delayed, restricted or changed due to maintenance, technical issues, network conditions, security events, third-party provider failures or operational decisions.') }}
                        </p>
                    </section>

                    <section id="third-parties">
                        <h2>{{ __('5. Third-Party Services') }}</h2>
                        <p>
                            {{ __('The website or platform may link to, integrate with or depend on third-party services such as wallet providers, analytics tools, payment providers, blockchain networks, infrastructure services or external websites. We do not control those third parties and are not responsible for their content, availability, security, policies or performance.') }}
                        </p>
                    </section>

                    <section id="liability">
                        <h2>{{ __('6. Limitation Of Liability') }}</h2>
                        <p>
                            {{ __('To the maximum extent permitted by applicable law, :app, its operators, affiliates, contributors and service providers will not be liable for any direct, indirect, incidental, consequential or special loss arising from access to or use of the website, platform, digital assets, marketplace features or linked services.', ['app' => config('app.name')]) }}
                        </p>
                    </section>

                    <section id="responsibility">
                        <h2>{{ __('7. User Responsibility') }}</h2>
                        <p>
                            {{ __('Users are responsible for their own account security, wallet security, private keys, passwords, transaction decisions, marketplace activity and compliance with applicable laws. Users should not participate in any activity they do not understand or cannot afford to risk.') }}
                        </p>
                    </section>

                    <section id="changes">
                        <h2>{{ __('8. Changes To This Disclaimer') }}</h2>
                        <p>
                            {{ __('We may update this Disclaimer from time to time to reflect changes in the platform, business operations, legal requirements or risk disclosures. The version published on this page is the current version.') }}
                        </p>
                    </section>
                </article>
            </div>
        </section>
    </main>
@stop
