<?php

$static = static fn (string $view, string $title, string $description): array => [
    'view' => "v2.pages.{$view}",
    'title' => $title,
    'description' => $description,
    'projection' => false,
];

$projected = static fn (string $view, string $title, string $description): array => [
    'view' => "v2.pages.{$view}",
    'title' => $title,
    'description' => $description,
    'projection' => true,
];

return [
    'homepage' => [...$static('homepage', 'Squadex | Football Manager Platform', 'Build clubs, follow simulated football competitions and explore the Squadex ecosystem.'), 'projection' => 'optional'],
    'about' => $static('about', 'About Squadex', 'Learn about the Squadex football management platform.'),
    'contact' => $static('contact', 'Contact Squadex', 'Contact the Squadex team.'),
    'game' => $static('game', 'Squadex Game', 'Explore the Squadex football management game.'),
    'status' => $static('status', 'Squadex Status', 'Check the availability of Squadex public services.'),
    'changelog' => $static('changelog', 'Squadex Changelog', 'Review Squadex product and public-site updates.'),
    'guides' => $static('guides', 'Squadex Guides', 'Read guides for the Squadex ecosystem.'),
    'insights' => $static('insights', 'Squadex Insights', 'Explore football simulation insights from Squadex.'),
    'highlights' => $static('highlights', 'Squadex Highlights', 'Review notable Squadex match moments.'),
    'stories' => $static('stories', 'Squadex Stories', 'Read stories from the Squadex football ecosystem.'),
    'token' => [...$static('token', 'Squadex Token', 'Official public information about the Squadex token.'), 'projection' => 'optional'],
    'tokenomics' => $static('tokenomics', 'Squadex Tokenomics', 'Explore Squadex token supply, allocation, utility and distribution.'),
    'token-roadmap' => $static('token-roadmap', 'Squadex Token Roadmap', 'Explore planned Squadex token milestones.'),
    'token-transparency' => $static('token-transparency', 'Squadex Token Transparency', 'Review official Squadex token transparency information.'),
    'presale' => $static('presale', 'Squadex Presale', 'Official information and safety guidance for a future Squadex presale.'),
    'how-to-buy' => $static('how-to-buy', 'How to Buy Squadex', 'Read the official Squadex token buying and safety guide.'),
    'contract' => $static('contract', 'Squadex Token Contract', 'Verify official Squadex token contract information.'),
    'liquidity' => $static('liquidity', 'Squadex Liquidity', 'Review official Squadex liquidity information.'),
    'vesting' => $static('vesting', 'Squadex Vesting', 'Review Squadex token vesting and unlock information.'),
    'whitepaper' => $static('whitepaper', 'Squadex Whitepaper', 'Read the Squadex platform, ecosystem and token whitepaper.'),
    'privacy' => $static('privacy', 'Privacy Policy', 'Read the Squadex privacy policy.'),
    'cookie' => $static('cookie', 'Cookie Policy', 'Read the Squadex cookie policy.'),
    'terms' => $static('terms', 'Terms of Service', 'Read the Squadex terms of service.'),
    'kyc' => $static('kyc', 'KYC Policy', 'Read the Squadex know-your-customer policy.'),
    'disclaimer' => $static('disclaimer', 'Disclaimer', 'Read the Squadex public information disclaimer.'),
    'faq' => $static('faq', 'Squadex FAQ', 'Find answers to common questions about Squadex.'),
    'community' => $static('community-page', 'Squadex Community', 'Follow official Squadex community channels and programmes.'),
    'discord' => $static('community-page', 'Squadex Discord', 'Find the official Squadex Discord community channel.'),
    'twitter' => $static('community-page', 'Squadex on X', 'Find official Squadex social updates.'),
    'referral' => $static('community-page', 'Squadex Referral Programme', 'Learn about Squadex community referrals.'),
    'ambassadors' => $static('community-page', 'Squadex Ambassadors', 'Learn about the Squadex ambassador programme.'),
    'partners' => $static('community-page', 'Squadex Partners', 'Learn about Squadex ecosystem partnerships.'),
    'investors' => $static('community-page', 'Squadex Investors', 'Explore public Squadex information for investors.'),
    'matches' => $projected('matches', 'Squadex Matches | Fixtures, Results & Football Simulations', 'Explore Squadex matches, fixtures, results, football simulations and match centre updates from the Squadex football manager ecosystem.'),
    'teams' => $projected('teams', 'Squadex Teams | Clubs, Squads & Football Manager Profiles', 'Explore Squadex teams, club profiles, squad identity, team performance concepts and future football manager ecosystem features.'),
    'players' => $projected('players', 'Squadex Players | Ratings, Clubs & Football Manager Data', 'Browse Squadex players, ratings, clubs, positions, market values and football manager profile data.'),
    'stats' => $projected('stats-overview', 'Squadex Statistics', 'Explore public Squadex football statistics.'),
    'team-stats' => $projected('team-stats', 'Team Statistics', 'Explore public Squadex team statistics.'),
    'player-stats-leaderboard' => $projected('player-stats-leaderboard', 'Player Statistics', 'Explore public Squadex player statistics.'),
    'match-stats-leaderboard' => $projected('match-stats-leaderboard', 'Match Statistics', 'Explore public Squadex match statistics.'),
    'top-players' => $projected('top-players', 'Top Players', 'Explore top Squadex players.'),
    'top-players-2026' => $projected('top-players-2026', 'Top Players 2026', 'Explore top Squadex players for 2026.'),
    'best-teams' => $projected('best-teams', 'Best Teams 2026', 'Explore the best Squadex teams for 2026.'),
    'football-predictions' => $projected('football-predictions', 'Football Predictions', 'Explore public Squadex football predictions.'),
    'champions-league-results' => $projected('champions-league-results', 'Champions League Results', 'Explore simulated Champions League results.'),
    'league-simulations' => $projected('league-simulations', 'League Simulations', 'Explore public Squadex league simulations.'),
    'league-results' => $projected('league-results', 'League Results', 'Explore public Squadex league results.'),
    'league-season' => $projected('league-season', 'League Season', 'Explore a public Squadex league season.'),
    'competition-season' => $projected('competition-season', 'Competition Season', 'Explore a public Squadex competition season.'),
    'country' => $projected('country', 'Country', 'Explore public Squadex football data by country.'),
    'city' => $projected('city', 'City', 'Explore public Squadex football data by city.'),
    'season' => $projected('season', 'Season', 'Explore a public Squadex season.'),
    'standings' => $projected('standings', 'Standings', 'Explore public Squadex standings.'),
    'team-form' => $projected('team-form', 'Team Form', 'Explore public Squadex team form.'),
    'match-team-analysis' => $projected('match-team-analysis', 'Match Analysis', 'Explore public Squadex match analysis.'),
    'team-analysis' => $projected('team-analysis', 'Team Analysis', 'Explore public Squadex team analysis.'),
    'compare-teams' => $projected('compare-teams', 'Compare Teams', 'Compare public Squadex team data.'),
    'player-matches' => $projected('player-matches', 'Player Matches', 'Explore public match history for a player.'),
    'player-stats' => $projected('player-stats', 'Player Stats', 'Explore public statistics for a player.'),
    'news' => $projected('news', 'Latest Squadex News', 'Read the latest Squadex news.'),
    'news-details' => $projected('news-details', 'Squadex News', 'Read a Squadex news article.'),
    'blog' => $projected('news', 'Squadex Blog', 'Read the latest Squadex blog posts.'),
    'blog-details' => $projected('news-details', 'Squadex Blog', 'Read a Squadex blog post.'),
    'marketplace' => $projected('marketplace', 'Player Marketplace', 'Scout listed players, compare ratings, review market value and secure new talent for your club.'),
    'marketplace-clubs' => $projected('marketplace-clubs', 'Club Marketplace', 'Acquire listed clubs with established locations, league access and operational football infrastructure.'),
    'marketplace-stadiums' => $projected('marketplace-stadiums', 'Stadium Marketplace', 'Browse stadium assets by capacity, opening year and asking price for long-term club growth.'),
    'tournaments' => $projected('tournaments', 'Squadex Tournaments', 'Explore public Squadex tournaments.'),
    'leaderboards' => $projected('leaderboards', 'Squadex Leaderboards', 'Explore public Squadex leaderboards.'),
    'goals-leaderboard' => $projected('goals-leaderboard', 'Goals Leaderboard', 'Explore the Squadex goals leaderboard.'),
    'xg-leaderboard' => $projected('xg-leaderboard', 'xG Leaderboard', 'Explore the Squadex expected-goals leaderboard.'),
    'records' => $projected('records', 'Squadex Records', 'Explore public Squadex football records.'),
    'player-details' => $projected('player-details', 'Player Profile', 'Explore a public Squadex player profile.'),
    'match-details' => $projected('match-details', 'Match Details', 'Explore public Squadex match details.'),
    'match-stats' => $projected('match-stats', 'Match Stats', 'Explore public Squadex match statistics.'),
    'match-lineups' => $projected('match-lineups', 'Match Lineups', 'Explore public Squadex match lineups.'),
    'match-timeline' => $projected('match-timeline', 'Match Timeline', 'Explore the public timeline for a Squadex match.'),
    'match-ratings' => $projected('match-ratings', 'Match Ratings', 'Explore public Squadex match ratings.'),
    'match-analysis' => $projected('match-analysis', 'Match Analysis', 'Explore public Squadex match analysis.'),
    'match-predictions' => $projected('match-predictions', 'Match Predictions', 'Explore public Squadex match predictions.'),
    'club' => $projected('club', 'Club Profile', 'Explore a public Squadex club profile.'),
];
